import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.locator('body').click();
  await page.locator('body').click();
  await page.goto('https://rahulshettyacademy.com/client/#/auth/login');
  await page.getByRole('textbox', { name: 'email@example.com' }).click();
  await page.getByRole('textbox', { name: 'email@example.com' }).fill('ahmed.adelazab202@gmail.com');
  await page.getByRole('textbox', { name: 'email@example.com' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'enter your passsword' }).click();
  await page.getByRole('textbox', { name: 'enter your passsword' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'enter your passsword' }).fill('A');
  await page.getByRole('textbox', { name: 'enter your passsword' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'enter your passsword' }).fill('Ahmed12345');
  await page.getByRole('textbox', { name: 'enter your passsword' }).press('Enter');
  await page.getByRole('button', { name: ' Add To Cart' }).nth(1).click();
  await page.locator('.ngx-spinner-overlay').click();
  await page.getByRole('button', { name: '   Cart' }).click();
  await page.getByRole('button', { name: 'Checkout❯' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('1234 4321 1234 4321');
  await page.getByRole('combobox').first().selectOption('11');
  await page.getByRole('combobox').nth(1).selectOption('22');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('356');
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).press('CapsLock');
  await page.getByRole('textbox').nth(2).fill('A');
  await page.getByRole('textbox').nth(2).press('CapsLock');
  await page.getByRole('textbox').nth(2).fill('Ahmed ');
  await page.getByRole('textbox').nth(2).press('CapsLock');
  await page.getByRole('textbox').nth(2).fill('Ahmed A');
  await page.getByRole('textbox').nth(2).press('CapsLock');
  await page.getByRole('textbox').nth(2).fill('Ahmed Adel');
  await page.locator('input[name="coupon"]').click();
  await page.locator('input[name="coupon"]').fill('1234');
  await page.getByRole('button', { name: 'Apply Coupon' }).click();
  await page.getByText('Place Order').click();
  await page.getByRole('textbox', { name: 'Select Country' }).click();
  await page.getByRole('textbox', { name: 'Select Country' }).click();
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox', { name: 'Select Country' }).click();
  await page.getByRole('textbox', { name: 'Select Country' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Select Country' }).fill('G');
  await page.getByRole('textbox', { name: 'Select Country' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Select Country' }).fill('Ger');
  await page.getByRole('button', { name: ' Germany' }).click();
  await page.getByText('Place Order').click();
});